# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/kondal/yocto_labs/poky/meta \
  /home/kondal/yocto_labs/poky/meta-poky \
  /home/kondal/yocto_labs/poky/meta-yocto-bsp \
  /home/kondal/yocto_labs/meta-raspberrypi \
  /home/kondal/yocto_labs/meta-openembedded/meta-oe \
  /home/kondal/yocto_labs/meta-openembedded/meta-python \
  /home/kondal/yocto_labs/meta-openembedded/meta-networking \
  /home/kondal/yocto_labs/meta-openembedded/meta-multimedia \
  /home/kondal/yocto_labs/meta-BKM-5 \
  "
